// Type declarations for tools/codemap/lib.mjs.
// The runtime module is pure Node ESM (no deps). These types let the TypeScript
// plugin tools (tools/code_memory.ts, tools/codemap_health.ts) typecheck against
// `await import("./codemap/lib.mjs")` without pulling in the JS source.

export interface CodemapCounts {
  files: number
  symbols: number
  nodes: number
  edges: number
  secretFlagged: number
}

// Optional richer-parser provenance. Present when generated by an engine build
// that probes for the TypeScript compiler API and a Python `ast` subprocess.
// These fields do NOT feed node/edge digests, so they cannot break reproducible
// integrity (they record environment/availability, stable per host+content).
export interface CodemapParserUsage {
  jsAst: number
  jsRegex: number
  pyAst: number
  pyRegex: number
  text: number
  binary: number
  secret: number
  large: number
}

export interface CodemapParserInfo {
  typescript: { available: boolean; version: string | null }
  python: { available: boolean; bin: string | null }
  usage: CodemapParserUsage
}

export interface CodemapManifest {
  version: string
  generator: string
  root: string
  generatedAt: string
  counts: CodemapCounts
  files: Record<string, { hash: string | null; mtimeMs: number; nodes: number; secretFlag: boolean }>
  timingsMs: { scan: number; extract: number; persist: number; total: number }
  digests: { nodes: string; edges: string }
  parsers?: CodemapParserInfo
}

export interface CodemapResult {
  ok: boolean
  markdown: string
  error?: string
}

export interface GenerateResult extends CodemapResult {
  manifest?: CodemapManifest
  generatedAt?: string
}

export interface RecallEdgeRef {
  type: string
  direction: "out" | "in"
  target?: string
  source?: string
  targetStatus: string
}

export interface RecallResultItem {
  node: Record<string, unknown>
  edges: { out: RecallEdgeRef[]; in: RecallEdgeRef[] }
}

export interface RecallResult extends CodemapResult {
  manifest?: CodemapManifest
  results?: RecallResultItem[]
  count?: number
  ms?: number
  missing?: boolean
  query?: string
}

export interface HealthResult extends CodemapResult {
  status?: "ok" | "stale" | "missing" | "drift"
  health?: Record<string, unknown>
  manifest?: CodemapManifest
}

export interface BenchResult extends CodemapResult {
  ok: boolean
  root: string
  out: string
  query: string
  generateMs: number
  recallMs: number
  totalMs: number
  speedup: number | null
  counts: CodemapCounts | null
  recallMatches: number | null
  genError: string | null
  recError: string | null
}

export function generateCodemap(opts?: {
  root?: string
  out?: string
  limit?: number
}): Promise<GenerateResult>

export function recallCodemap(opts?: {
  root?: string
  out?: string
  query?: string
  limit?: number
}): Promise<RecallResult>

export function healthCodemap(opts?: {
  root?: string
  out?: string
  staleThreshold?: number
}): Promise<HealthResult>

export function benchCodemap(opts?: {
  root?: string
  out?: string
  query?: string
  limit?: number
}): Promise<BenchResult>
